from typing import Dict, Any, List
from pathlib import Path

def hex_to_ass_color(hex_str: str, alpha: str = "00") -> str:
    """
    Convert CSS hex color '#RRGGBB' to ASS color format '&HAABBGGRR'.
    """
    hex_clean = hex_str.lstrip("#")
    if len(hex_clean) == 3:
        hex_clean = "".join([c * 2 for c in hex_clean])
    if len(hex_clean) != 6:
        return f"&H{alpha}FFFFFF&"
    r = hex_clean[0:2]
    g = hex_clean[2:4]
    b = hex_clean[4:6]
    return f"&H{alpha}{b.upper()}{g.upper()}{r.upper()}&"

def format_ass_time(seconds: float) -> str:
    """Format seconds into ASS timestamp H:MM:SS.cs (centiseconds)."""
    seconds = max(0.0, seconds)
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    cs = int(round((seconds - int(seconds)) * 100))
    if cs >= 100:
        cs = 99
    return f"{hrs}:{mins:02d}:{secs:02d}.{cs:02d}"

def format_srt_time(seconds: float) -> str:
    """Format seconds into SRT timestamp HH:MM:SS,mmm."""
    seconds = max(0.0, seconds)
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    ms = int(round((seconds - int(seconds)) * 1000))
    if ms >= 1000:
        ms = 999
    return f"{hrs:02d}:{mins:02d}:{secs:02d},{ms:03d}"

def format_vtt_time(seconds: float) -> str:
    """Format seconds into WebVTT timestamp HH:MM:SS.mmm."""
    return format_srt_time(seconds).replace(",", ".")

class SubtitleGenerator:
    @staticmethod
    def _chunk_lyrics(lyrics: List[Dict[str, Any]], format_type: str) -> List[List[Dict[str, Any]]]:
        """Groups lyrics lines into chunks based on format (stanza=4 lines, sentence=2 lines, line=1 line)."""
        if not lyrics:
            return []
        if format_type == "stanza":
            chunk_size = 4
        elif format_type == "sentence":
            chunk_size = 2
        else:
            chunk_size = 1

        chunks = []
        current_chunk = []
        for line in lyrics:
            if current_chunk and len(current_chunk) >= chunk_size:
                chunks.append(current_chunk)
                current_chunk = []
            current_chunk.append(line)
        if current_chunk:
            chunks.append(current_chunk)
        return chunks

    @staticmethod
    def generate_ass(canonical_data: Dict[str, Any], output_path: Path) -> Path:
        """
        Generates an ASS subtitle file from canonical JSON project data.
        Supports Whole Stanza, Sentence Couplet, and Single Line formats.
        """
        style_cfg = canonical_data.get("style", {})
        font_name = style_cfg.get("font", "Caveat")
        font_size = style_cfg.get("font_size", 34)
        primary_hex = style_cfg.get("primary_color", "#FFFFFF")
        highlight_hex = style_cfg.get("highlight_color", "#10B981")
        outline = style_cfg.get("outline", 2)
        shadow = style_cfg.get("shadow", 1)
        position = style_cfg.get("position", "center")
        text_align = style_cfg.get("text_align", "center")
        mode = style_cfg.get("mode", "karaoke")
        lyrics_format = style_cfg.get("format") or canonical_data.get("render", {}).get("lyrics_format", "stanza")

        # Alignment: Numpad notation
        # Top: 7 (left), 8 (center), 9 (right)
        # Center: 4 (left), 5 (center), 6 (right)
        # Bottom: 1 (left), 2 (center), 3 (right)
        align_map = {
            ("top", "left"): 7,
            ("top", "center"): 8,
            ("top", "right"): 9,
            ("center", "left"): 4,
            ("center", "center"): 5,
            ("center", "right"): 6,
            ("bottom", "left"): 1,
            ("bottom", "center"): 2,
            ("bottom", "right"): 3,
        }
        alignment = align_map.get((position, text_align), 5)
        margin_v = 15 if position == "center" else 60

        primary_color = hex_to_ass_color(primary_hex, "00")
        secondary_color = hex_to_ass_color(highlight_hex, "00")
        outline_color = "&H00000000&"
        back_color = "&H64000000&"

        render_cfg = canonical_data.get("render", {})
        target_aspect = render_cfg.get("aspect_ratio") or canonical_data.get("style", {}).get("aspectRatio", "16:9")
        if target_aspect == "9:16":
            play_res_x, play_res_y = 1080, 1920
        elif target_aspect == "1:1":
            play_res_x, play_res_y = 1080, 1080
        elif target_aspect == "4:5":
            play_res_x, play_res_y = 1080, 1350
        else:
            media_cfg = canonical_data.get("media", {})
            play_res_x = media_cfg.get("width", 1920)
            play_res_y = media_cfg.get("height", 1080)

        title_font_size = max(42, int(font_size * 1.35))
        header = f"""[Script Info]
; Script generated by LyricSync Studio
Title: LyricSync Karaoke Video
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: {play_res_x}
PlayResY: {play_res_y}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{font_name},{font_size},{primary_color},{secondary_color},{outline_color},{back_color},-1,0,0,0,100,100,0,0,1,{outline},{shadow},{alignment},40,40,{margin_v},1
Style: Highlight,{font_name},{font_size},{secondary_color},{primary_color},{outline_color},{back_color},-1,0,0,0,100,100,0,0,1,{outline},{shadow},{alignment},40,40,{margin_v},1
Style: Title,{font_name},{title_font_size},{primary_color},{secondary_color},{outline_color},{back_color},-1,0,0,0,100,100,0,0,1,{outline + 1},{shadow + 1},5,40,40,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        events = []
        lyrics = canonical_data.get("lyrics", [])

        # Song Title Reveal with Typewriter Effect during intro before lyrics start
        song_title = (
            canonical_data.get("project", {}).get("name")
            or canonical_data.get("meta", {}).get("title")
            or canonical_data.get("name")
            or ""
        ).strip()

        first_lyric_start = float(lyrics[0].get("start", 0.0)) if lyrics else 5.0
        if first_lyric_start >= 0.8 and song_title:
            intro_end = min(4.5, first_lyric_start - 0.25)
            if intro_end >= 0.8:
                typing_end = max(0.6, intro_end * 0.72)
                n_chars = len(song_title)
                for i in range(n_chars):
                    t_s = (i / n_chars) * typing_end
                    t_e = ((i + 1) / n_chars) * typing_end
                    s_str = format_ass_time(t_s)
                    e_str = format_ass_time(t_e)
                    slice_text = song_title[:i + 1]
                    events.append(
                        f"Dialogue: 1,{s_str},{e_str},Title,,0,0,0,,{{\\c{secondary_color}}}NOW PLAYING\\N{{\\c{primary_color}}}{slice_text}|"
                    )
                # Hold completed title before first lyric starts
                s_hold = format_ass_time(typing_end)
                e_hold = format_ass_time(intro_end)
                events.append(
                    f"Dialogue: 1,{s_hold},{e_hold},Title,,0,0,0,,{{\\fad(0,250)}}{{\\c{secondary_color}}}NOW PLAYING\\N{{\\c{primary_color}}}{song_title}|"
                )

        chunks = SubtitleGenerator._chunk_lyrics(lyrics, lyrics_format)


        if mode == "karaoke":
            for chunk in chunks:
                if not chunk:
                    continue
                raw_chunk_start = float(chunk[0].get("start", 0.0))
                raw_chunk_end = float(chunk[-1].get("end", 0.0))
                event_start_cs = int(round(raw_chunk_start * 100))
                event_end_cs = int(round(raw_chunk_end * 100))
                if event_end_cs <= event_start_cs:
                    event_end_cs = event_start_cs + 100

                chunk_start = format_ass_time(raw_chunk_start)
                chunk_end = format_ass_time(float(event_end_cs) / 100.0)

                current_rel_cs = 0
                line_parts = []

                for line in chunk:
                    words = line.get("words", [])
                    karaoke_text_parts = []
                    for w in words:
                        w_start_raw = float(w.get("start", raw_chunk_start))
                        w_end_raw = float(w.get("end", w_start_raw + 0.3))
                        w_start_cs = int(round(w_start_raw * 100)) - event_start_cs
                        w_end_cs = int(round(w_end_raw * 100)) - event_start_cs

                        gap_cs = w_start_cs - current_rel_cs
                        if gap_cs > 0:
                            # Insert silence duration so karaoke highlight doesn't run ahead
                            karaoke_text_parts.append(f"{{\\k{gap_cs}}}")
                            current_rel_cs += gap_cs
                        elif gap_cs < 0:
                            w_start_cs = current_rel_cs

                        duration_cs = max(1, w_end_cs - w_start_cs)
                        word_str = w.get("text", "")
                        karaoke_text_parts.append(f"{{\\kf{duration_cs}}}{word_str} ")
                        current_rel_cs += duration_cs

                    line_parts.append("".join(karaoke_text_parts).rstrip())

                full_chunk_text = "\\N".join(line_parts)
                events.append(f"Dialogue: 0,{chunk_start},{chunk_end},Default,,0,0,0,,{full_chunk_text}")
        else:
            for chunk in chunks:
                if not chunk:
                    continue
                for line_idx, line in enumerate(chunk):
                    words = line.get("words", [])
                    for active_word_idx, active_word in enumerate(words):
                        w_start = format_ass_time(active_word["start"])
                        w_end = format_ass_time(active_word["end"])

                        chunk_lines_styled = []
                        for curr_l_idx, curr_line in enumerate(chunk):
                            curr_words = curr_line.get("words", [])
                            line_tokens = []
                            for curr_w_idx, w in enumerate(curr_words):
                                if curr_l_idx == line_idx and curr_w_idx == active_word_idx:
                                    line_tokens.append(f"{{\\c{secondary_color}}}{w['text']}{{\\c{primary_color}}}")
                                else:
                                    line_tokens.append(w["text"])
                            chunk_lines_styled.append(" ".join(line_tokens))

                        dialogue_text = "\\N".join(chunk_lines_styled)
                        events.append(f"Dialogue: 0,{w_start},{w_end},Default,,0,0,0,,{dialogue_text}")

        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(header + "\n".join(events) + "\n")

        return output_path

    @staticmethod
    def generate_srt(canonical_data: Dict[str, Any], output_path: Path) -> Path:
        """Generates standard SRT subtitles."""
        lines = canonical_data.get("lyrics", [])
        content = []
        for idx, line in enumerate(lines, 1):
            s_time = format_srt_time(line.get("start", 0.0))
            e_time = format_srt_time(line.get("end", 0.0))
            content.append(f"{idx}\n{s_time} --> {e_time}\n{line.get('text', '')}\n")

        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(content))
        return output_path

    @staticmethod
    def generate_vtt(canonical_data: Dict[str, Any], output_path: Path) -> Path:
        """Generates standard WebVTT subtitles."""
        lines = canonical_data.get("lyrics", [])
        content = ["WEBVTT\n"]
        for idx, line in enumerate(lines, 1):
            s_time = format_vtt_time(line.get("start", 0.0))
            e_time = format_vtt_time(line.get("end", 0.0))
            content.append(f"{idx}\n{s_time} --> {e_time}\n{line.get('text', '')}\n")

        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(content))
        return output_path
